rails_workspace/private-events/config/routes.rb
Rails.application.routes.draw do
  get 'events/new', to: 'events#new'
  get 'events/show', to: 'events#show'
  get 'events/index', to: 'events#index'
 post 'events/new', to: 'events#create'

get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

end

rails_workspace/private-events/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_workspace/private-events/app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, :class_name => "User"
	has_many :event_attendings, :foreign_key => :attended_event_id
	has_many :attendees, :through => :event_attendings, :source => :event_attending
end

rails_workspace/private-events/app/models/event_attending.rb
class EventAttending < ApplicationRecord
	belongs_to :attendee, :class_name => "User"
	belongs_to :attended_event, :class_name => "Event"
end

rails_workspace/private-events/app/models/user.rb
class User < ApplicationRecord
	has_many :events, :foreign_key => :creator_id, :class_name => "Event"
	has_many :event_attendings, :foreign_key => :attendee_id
	has_many :attended_events, :through => :event_attendings, :source => :attended_event
end

rails_workspace/private-events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

rails_workspace/private-events/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  	@event = Event.new
  end

  def create
  	if @event = current_user.events.create(event_params)
  		flash[:sucess] = "You created an event!"
  		redirect_to events_show_path
  	else
  		flash.now[:danger] = "Try again"
  		render events_new_path
  	end
  end

  def show
  	@event = Event.find_by(params[:id])
  end

  def index
  	@events = Event.all
  end

  private

    def event_params
    	params.require(:event).permit(:name, :place, :day, :desc)
    end
end

rails_workspace/private-events/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	@user = User.find_by(params[:username])
  	if @user
  		log_in @user
  		redirect_to @user
  	else
  		flash.now[:warning] = "Try again please"
  		render new_user_path
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to login_path
  end
end

rails_workspace/private-events/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			redirect_to @user
		else
			flash.now[:warning] = "Try again please"
			render new_user_path
		end
	end

	def show
		@user = User.find_by(params[:id])
	end

	def index
		@users = User.all
	end



	private

	  def user_params
	  	params.require(:user).permit(:username)
	  end


end

rails_workspace/private-events/app/helpers/application_helper.rb
module ApplicationHelper
	
end

rails_workspace/private-events/app/helpers/events_helper.rb
module EventsHelper
end

rails_workspace/private-events/app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if user_id = session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		end
	end
	
	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

end

rails_workspace/private-events/app/helpers/users_helper.rb
module UsersHelper
end

rails_workspace/private-events/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h1>Private Events!! - <%= yield(:subtitle) %></h1>

  <body>
  	<nav>
  		<ul>
  			<% if logged_in? %>
  				<p>Profile: <%= @current_user.username %></p>
  				<li><%= link_to "logout", logout_path, method: "delete" %></li>
  				<li><%= link_to "All Users", users_path %></li>
  			<% else %>
  				<li><%= link_to "login", login_path %></li>
  				<li><%= link_to "Signup!", new_user_path %></li>
  			<% end %>
  	<% flash.each do |key, value| %>
        <%= value %>
      <% end %>
    <%= yield %>
  </body>
</html>

rails_workspace/private-events/app/views/users/index.html.erb
<% provide(:subtitle, "All Users") %>

<ul>
	<% @users.each do |user| %>
		<li><%= user.username %></li>
	<% end %>
</ul>

rails_workspace/private-events/app/views/users/new.html.erb
<% provide(:subtitle, "Register") %>

<%= form_for(@user) do |f| %>

	<%= f.label :username %>
	<%= f.text_field :username %> 
	<%= f.submit "Register!" %>
<% end %>

rails_workspace/private-events/app/views/users/show.html.erb
<% provide(:subtitle, @user.username) %>